# Generated by Django 4.0 on 2023-08-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermittedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('type_of_log', models.CharField(max_length=255, verbose_name='logon/logoff')),
                ('userdomain', models.CharField(max_length=255, verbose_name='userdomain')),
                ('hostname', models.CharField(max_length=255, verbose_name='hostname')),
                ('ipaddress', models.CharField(max_length=255, verbose_name='ip address')),
                ('type_of_service', models.CharField(max_length=255, verbose_name='Тип Входа в систему')),
                ('time_login', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('localdatetime', models.DateTimeField(verbose_name='localdatetime')),
                ('session_ip', models.CharField(max_length=255, verbose_name='IP машины с которой пришёл запрос')),
            ],
        ),
    ]
