# Generated by Django 4.0 on 2023-07-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alienuser',
            name='session_ip',
            field=models.CharField(default=1, max_length=255, verbose_name='IP машины с которой пришёл запрос'),
            preserve_default=False,
        ),
    ]
