# Generated by Django 4.0 on 2023-08-05 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_logs', '0002_alienuser_session_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='alienuser',
            name='localdatetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='localdatetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permitteduser',
            name='localdatetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='localdatetime'),
            preserve_default=False,
        ),
    ]
